appname: "TRunner"
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: template_toolkit
engines:
  template_toolkit:
    ENCODING: utf8
    start_tag: '[%'
    end_tag: '%]'

smolder:
  server: ""
  username: ""
  password: ""
  project_id: ""
